/** Deterministic sample data used by unit tests and the demo/visual mode.
 *  Shapes mirror the database views/tables. Never used in production. */
import type { OrderFinancial, Expense, Payment, Refund, ProductSale, Order, Product, ProductCategory, BusinessSettings, TaxSettings, Customer, DeliveryRecord } from "../lib/types";

const day = (n: number) => new Date(Date.now() - n * 86400000).toISOString();
export const CATS: ProductCategory[] = [{ id: "c1", name: "Feteer", sort_order: 1 }, { id: "c2", name: "Soups", sort_order: 2 }, { id: "c3", name: "Cakes", sort_order: 3 }];
export const PRODUCTS: Product[] = [
  { id: "p1", slug: "feteer-meshaltet", name: "Feteer Meshaltet", name_ar: "", category_id: "c1", description: "", image_url: "", selling_price: 14, is_active: true, tax_status: "taxable", packaging_cost: 1.25, labor_minutes: 20, other_direct_cost: 0, ingredient_cost: 2.1, created_at: day(60), updated_at: day(1), deleted_at: null, product_categories: { name: "Feteer" } },
  { id: "p2", slug: "lentil-soup", name: "Lentil Soup", name_ar: "", category_id: "c2", description: "", image_url: "", selling_price: 7, is_active: true, tax_status: "taxable", packaging_cost: 0.6, labor_minutes: 5, other_direct_cost: 0, ingredient_cost: 0.9, created_at: day(60), updated_at: day(1), deleted_at: null, product_categories: { name: "Soups" } },
  { id: "p3", slug: "round-cake", name: "Small Round Cake", name_ar: "", category_id: "c3", description: "", image_url: "", selling_price: 12, is_active: true, tax_status: "nontaxable", packaging_cost: 2, labor_minutes: 25, other_direct_cost: 0, ingredient_cost: 3.5, created_at: day(60), updated_at: day(1), deleted_at: null, product_categories: { name: "Cakes" } },
];
export const SETTINGS: BusinessSettings = { id: 1, business_name: "Pharaoh's Bites", owner_name: "Owner", address: "", phone: "+1 787-968-4078", whatsapp_number: "17879684078", email: "", logo_url: "", currency: "USD", timezone: "America/Chicago", order_number_prefix: "PB", default_delivery_rate_per_mile: 1.5, default_mileage_cost_per_mile: 0.67, default_labor_rate_per_hour: 15, include_owner_labor: false, low_margin_warning_pct: 0.3, minimum_order_amount: 20, default_whatsapp_message: "Hi {name}, order {order_number}: delivery {delivery_fee}, total {total}.", cancellation_rules: "", updated_at: day(1) };
export const TAX: TaxSettings = { id: 1, default_tax_rate: 0.0825, prices_include_tax: false, filing_frequency: "quarterly", next_due_date: new Date(Date.now() + 10 * 86400000).toISOString().slice(0, 10), reminder_days_before: 14, jurisdiction_note: "Texas", updated_at: day(1) };

// order_financials rows: o1 completed, o2 completed, o3 pending, o4 cancelled, o5 refunded, o6 confirmed partially paid
export const FIN: OrderFinancial[] = [
  { id: "o1", order_number: "PB-2026-00001", created_at: day(3), completed_at: day(2), status: "completed", payment_status: "paid", payment_method: "zelle", delivery_method: "delivery", customer_id: "u1", customer_name: "Yasmine F.", customer_phone: "2145550101", gross_product_revenue: 35, discount: 5, net_product_sales: 30, delivery_revenue: 8, tax_amount: 2.48, total: 40.48, amount_paid: 40.48, amount_refunded: 0, balance_due: 0, cogs: 8.2, packaging_cost: 3.1, labor_cost: 11.25, delivery_cost: 4.35, items_count: 3, gross_profit: 21.8, contribution_profit: 25.45, deleted_at: null },
  { id: "o2", order_number: "PB-2026-00002", created_at: day(2), completed_at: day(1), status: "completed", payment_status: "paid", payment_method: "venmo", delivery_method: "pickup", customer_id: "u2", customer_name: "Mark W.", customer_phone: "4695550102", gross_product_revenue: 24, discount: 0, net_product_sales: 24, delivery_revenue: 0, tax_amount: 0, total: 24, amount_paid: 24, amount_refunded: 0, balance_due: 0, cogs: 11, packaging_cost: 4, labor_cost: 12.5, delivery_cost: 0, items_count: 2, gross_profit: 13, contribution_profit: 13, deleted_at: null },
  { id: "o3", order_number: "PB-2026-00003", created_at: day(0), completed_at: null, status: "pending_whatsapp_confirmation", payment_status: "unpaid", payment_method: null, delivery_method: "delivery", customer_id: "u1", customer_name: "Yasmine F.", customer_phone: "2145550101", gross_product_revenue: 14, discount: 0, net_product_sales: 14, delivery_revenue: 0, tax_amount: 1.16, total: 15.16, amount_paid: 0, amount_refunded: 0, balance_due: 15.16, cogs: 3.35, packaging_cost: 1.25, labor_cost: 5, delivery_cost: 0, items_count: 1, gross_profit: 10.65, contribution_profit: 10.65, deleted_at: null },
  { id: "o4", order_number: "PB-2026-00004", created_at: day(1), completed_at: null, status: "cancelled", payment_status: "unpaid", payment_method: null, delivery_method: "delivery", customer_id: "u2", customer_name: "Mark W.", customer_phone: "4695550102", gross_product_revenue: 100, discount: 0, net_product_sales: 100, delivery_revenue: 10, tax_amount: 8.25, total: 118.25, amount_paid: 0, amount_refunded: 0, balance_due: 118.25, cogs: 30, packaging_cost: 5, labor_cost: 20, delivery_cost: 5, items_count: 5, gross_profit: 70, contribution_profit: 75, deleted_at: null },
  { id: "o5", order_number: "PB-2026-00005", created_at: day(4), completed_at: day(3), status: "refunded", payment_status: "partially_refunded", payment_method: "venmo", delivery_method: "delivery", customer_id: "u2", customer_name: "Mark W.", customer_phone: "4695550102", gross_product_revenue: 24, discount: 0, net_product_sales: 24, delivery_revenue: 5, tax_amount: 0, total: 29, amount_paid: 29, amount_refunded: 12, balance_due: 12, cogs: 11, packaging_cost: 4, labor_cost: 12.5, delivery_cost: 3, items_count: 2, gross_profit: 13, contribution_profit: 15, deleted_at: null },
  { id: "o6", order_number: "PB-2026-00006", created_at: day(1), completed_at: null, status: "confirmed", payment_status: "partially_paid", payment_method: "zelle", delivery_method: "delivery", customer_id: "u1", customer_name: "Yasmine F.", customer_phone: "2145550101", gross_product_revenue: 42, discount: 0, net_product_sales: 42, delivery_revenue: 8, tax_amount: 3.47, total: 53.47, amount_paid: 20, amount_refunded: 0, balance_due: 33.47, cogs: 10.05, packaging_cost: 3.75, labor_cost: 15, delivery_cost: 4.35, items_count: 3, gross_profit: 31.95, contribution_profit: 35.6, deleted_at: null },
];
export const EXPENSES: Expense[] = [
  { id: "e1", expense_date: day(5).slice(0, 10), vendor: "Costco", category_id: "x1", description: "Flour", amount_before_tax: 40, sales_tax_paid: 0, total_amount: 40, payment_method: "card", receipt_path: "", cost_type: "direct_product", product_id: null, order_id: null, notes: "", recurrence: "none", recurring_parent_id: null, created_at: day(5), updated_at: day(5), deleted_at: null, expense_categories: { name: "Ingredients" } },
  { id: "e2", expense_date: day(2).slice(0, 10), vendor: "Meta", category_id: "x2", description: "Ads", amount_before_tax: 25, sales_tax_paid: 0, total_amount: 25, payment_method: "card", receipt_path: "", cost_type: "operating", product_id: null, order_id: null, notes: "", recurrence: "monthly", recurring_parent_id: null, created_at: day(2), updated_at: day(2), deleted_at: null, expense_categories: { name: "Marketing" } },
  { id: "e3", expense_date: day(1).slice(0, 10), vendor: "Bank", category_id: "x3", description: "Fees", amount_before_tax: 3, sales_tax_paid: 0, total_amount: 3, payment_method: "other", receipt_path: "", cost_type: "operating", product_id: null, order_id: null, notes: "", recurrence: "none", recurring_parent_id: null, created_at: day(1), updated_at: day(1), deleted_at: null, expense_categories: { name: "Bank / payment fees" } },
];
export const PAYMENTS: Payment[] = [
  { id: "y1", order_id: "o1", paid_at: day(2), amount: 40.48, method: "zelle", reference: "Z1", notes: "", created_at: day(2), voided_at: null, orders: { order_number: "PB-2026-00001", customer_name: "Yasmine F." } },
  { id: "y2", order_id: "o2", paid_at: day(1), amount: 24, method: "venmo", reference: "", notes: "", created_at: day(1), voided_at: null, orders: { order_number: "PB-2026-00002", customer_name: "Mark W." } },
  { id: "y3", order_id: "o5", paid_at: day(3), amount: 29, method: "venmo", reference: "", notes: "", created_at: day(3), voided_at: null, orders: { order_number: "PB-2026-00005", customer_name: "Mark W." } },
  { id: "y4", order_id: "o6", paid_at: day(1), amount: 20, method: "zelle", reference: "", notes: "", created_at: day(1), voided_at: null, orders: { order_number: "PB-2026-00006", customer_name: "Yasmine F." } },
  { id: "y5", order_id: "o2", paid_at: day(1), amount: 99, method: "cash", reference: "mistake", notes: "", created_at: day(1), voided_at: day(1), orders: { order_number: "PB-2026-00002", customer_name: "Mark W." } },
];
export const REFUNDS: Refund[] = [{ id: "r1", order_id: "o5", payment_id: "y3", refunded_at: day(2), amount: 12, tax_portion: 0, method: "venmo", reason: "damaged", voided_at: null }];
export const SALES: ProductSale[] = [
  { product_id: "p1", product_name: "Feteer Meshaltet", category_id: "c1", created_at: day(3), completed_at: day(2), status: "completed", quantity: 2, refunded_qty: 0, line_total: 28, line_cost: 6.7, line_labor_cost: 10, line_discount: 4, order_id: "o1" },
  { product_id: "p2", product_name: "Lentil Soup", category_id: "c2", created_at: day(3), completed_at: day(2), status: "completed", quantity: 1, refunded_qty: 0, line_total: 7, line_cost: 1.5, line_labor_cost: 1.25, line_discount: 1, order_id: "o1" },
  { product_id: "p3", product_name: "Small Round Cake", category_id: "c3", created_at: day(2), completed_at: day(1), status: "completed", quantity: 2, refunded_qty: 0, line_total: 24, line_cost: 11, line_labor_cost: 12.5, line_discount: 0, order_id: "o2" },
  { product_id: "p1", product_name: "Feteer Meshaltet", category_id: "c1", created_at: day(0), completed_at: null, status: "pending_whatsapp_confirmation", quantity: 1, refunded_qty: 0, line_total: 14, line_cost: 3.35, line_labor_cost: 5, line_discount: 0, order_id: "o3" },
  { product_id: "p1", product_name: "Feteer Meshaltet", category_id: "c1", created_at: day(1), completed_at: null, status: "cancelled", quantity: 5, refunded_qty: 0, line_total: 70, line_cost: 16.75, line_labor_cost: 25, line_discount: 0, order_id: "o4" },
  { product_id: "p3", product_name: "Small Round Cake", category_id: "c3", created_at: day(4), completed_at: day(3), status: "refunded", quantity: 2, refunded_qty: 1, line_total: 24, line_cost: 11, line_labor_cost: 12.5, line_discount: 0, order_id: "o5" },
  { product_id: "p1", product_name: "Feteer Meshaltet", category_id: "c1", created_at: day(1), completed_at: null, status: "confirmed", quantity: 3, refunded_qty: 0, line_total: 42, line_cost: 10.05, line_labor_cost: 15, line_discount: 0, order_id: "o6" },
];
export const CUSTOMERS: Customer[] = [
  { id: "u1", name: "Yasmine F.", phone: "+1 (214) 555-0101", phone_normalized: "12145550101", email: "", status: "vip", internal_notes: "", merged_into_id: null, created_at: day(60), updated_at: day(1), deleted_at: null, customer_addresses: [{ id: "a1", customer_id: "u1", street: "1234 Elm St", apt: "", city: "Dallas", state: "TX", zip: "75201", instructions: "Ring bell", is_default: true }] },
  { id: "u2", name: "Mark W.", phone: "+1 (469) 555-0102", phone_normalized: "14695550102", email: "", status: "active", internal_notes: "", merged_into_id: null, created_at: day(60), updated_at: day(1), deleted_at: null, customer_addresses: [] },
];
export const ORDERS: Order[] = FIN.map((f) => ({
  id: f.id, order_number: f.order_number, checkout_token: null, source: "website", customer_id: f.customer_id, customer_name: f.customer_name, customer_phone: f.customer_phone,
  delivery_method: f.delivery_method, address_street: "1234 Elm St", address_apt: "", address_city: "Dallas", address_state: "TX", address_zip: "75201", delivery_instructions: "Ring bell", requested_at: null,
  status: f.status, payment_status: f.payment_status, payment_method: f.payment_method, subtotal: f.gross_product_revenue, discount: f.discount, discount_reason: "", delivery_fee: f.delivery_revenue, delivery_fee_customer_paid: true, delivery_subsidy: 0,
  tax_rate_applied: 0.0825, tax_amount: f.tax_amount, tax_manually_set: false, prices_include_tax: false, total: f.total, amount_paid: f.amount_paid, amount_refunded: f.amount_refunded, internal_notes: "", customer_notes: "",
  created_at: f.created_at, updated_at: f.created_at, confirmed_at: null, completed_at: f.completed_at, cancelled_at: null, deleted_at: null,
  order_items: SALES.filter((s) => s.order_id === f.id).map((s, i) => ({ id: f.id + "i" + i, order_id: f.id, product_id: s.product_id, product_name: s.product_name ?? "", options: "", quantity: s.quantity, unit_price: Number(s.line_total) / s.quantity, line_total: s.line_total, is_taxable: s.product_id !== "p3", unit_ingredient_cost: 2, unit_packaging_cost: 1, unit_labor_cost: 5, unit_other_cost: 0, refunded_qty: s.refunded_qty })),
  payments: PAYMENTS.filter((p) => p.order_id === f.id), refunds: REFUNDS.filter((r) => r.order_id === f.id),
  delivery_records: f.delivery_method === "delivery" ? [{ id: "d" + f.id, order_id: f.id, distance_miles: 6.5, fee_charged: f.delivery_revenue, actual_cost: f.delivery_cost, provider: "owner", driver: "", tracking_ref: "", status: "delivered", notes: "", updated_at: f.created_at }] : [],
  order_status_history: [{ id: "h" + f.id, order_id: f.id, from_status: null, to_status: "pending_whatsapp_confirmation", changed_by: null, note: "Order created (website)", created_at: f.created_at }],
}));
export const DELIVERIES: DeliveryRecord[] = ORDERS.flatMap((o) => (o.delivery_records as DeliveryRecord[]).map((d) => ({ ...d, orders: { order_number: o.order_number, customer_name: o.customer_name, address_street: o.address_street, address_city: o.address_city, created_at: o.created_at, delivery_fee: o.delivery_fee, delivery_fee_customer_paid: true, status: o.status } })));
